### ISSUE TITLE
用python SDK获取的日志数量不对

### ISSUE THREAD

**Issue by ntuwang** [aliyun/aliyun-log-python-sdk#10]
我用这个 脚本获取的 日志数量 很少 只有大概1分钟的数量,不管我怎么 选择 写
    From = int(time.time())-86400
    To = int(time.time())
函数 sample_get_logs
总是获得很少 日志数量,在web控制台上可以查到很多

**Comment by mayunlei** [comment]
SDK获取数据，每次最多100行,不指定行数的话，每次默认获取10行，需要翻页获取所有数据

**Comment by ntuwang** [comment]
如何 设置 默认获取 所有的数据 ?

**Comment by ntuwang** [comment]
好了,搞定了
