### ISSUE TITLE
jupyter notebook 中的 %fetch 容易 OOM, 是否可以支持 search 表达式? 

### ISSUE THREAD

**Issue by cupen** [aliyun/aliyun-log-python-sdk#138]
我参考的这份说明
https://aliyun-log-python-sdk.readthedocs.io/tutorials/tutorial_jupyter_magic_ext.html?highlight=jupyter#id13
看起来 fetch 目前只能按时间范围拉取全部日志, 而 pandas 又只能用内存, 很容易 OOM 啊.

**Comment by cupen** [comment]
看了下代码., 改起来还是比较容易的.  就是实现 search 表达式的工作量稍大一点.  但可以取个巧.

```python
# 自定义函数, 通过 locals["filter_func"](log) 来调用
def filter_func(log) -> bool:
    pass
```

```
%fetch 2019-8-31 0:0:0+8:0 ~ 2019-9-1 0:0:0+8:0   filter_func
```

**Comment by cupen** [comment]
囧,我加了 filter 之后,内存依然不减.
https://github.com/cupen/aliyun-log-python-sdk

**Comment by wjo1212** [comment]
@cupen 你好, 要估算下数据量, 先用小时间段看下dataframe的内存量, 再评估下过滤效果
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.memory_usage.html

**Comment by cupen** [comment]
@wjo1212  嗯.  谢谢回复.
我们的日志有点多, 数据分析所在的机器配置也比较低(8GB). 只按时间过滤的话, 只能查个把小时的数据.

但我加了个 fetch2 , 除了按时间, 还加了自定义过滤, 现在能工作了.
实现比较偷懒, 直接 eval cell code 创建了一个 filter .
```
%%fetch2 2019-9-1T0:0:0+8:0 ~ 2019-9-2T0:0:0+8:0
log['event'] == "login_success" and log["subevent"] != "fixdata"
```
https://github.com/cupen/aliyun-log-python-sdk/blob/master/aliyun/log/ext/jupyter_magic.py#L114

**Comment by cupen** [comment]
我突然觉得,直接用 web 控制台上所使用的 `search 表达式 | SQL ` 的查询方式更简单, 只获取结果, 不用担心 OOM.  感觉这个 jupyter notebook 可以支持下.
