### ISSUE TITLE
[IDEA] Can we get a full example for Aliyun OSS with fastAPI?

### ISSUE THREAD

**Issue by mr-od** [aliyun/aliyun-log-python-sdk#224]
As fastAPI is becoming more and more popular, i think people would like to know how they can integrate their fastAPI with Aliyun. There are so many examples for S3 integration with almost all the python frameworks. Thank you.

**Comment by cupen** [comment]
What is the fastAPI?

**Comment by mr-od** [comment]
I actually figured it out. I was able to implement it.
