### ISSUE TITLE
I have write a comsumer python lib for loghub. Is anyone need it ?

### ISSUE THREAD

**Issue by tinkpeng** [aliyun/aliyun-log-python-sdk#3]

**Comment by mayunlei** [comment]
@tinkpeng thank you for your accellent work. Could you please make a pull request to this project.

**Comment by wjo1212** [comment]
thanks for the contribution, i have refine the code basing on your version and make a PR
https://github.com/aliyun/aliyun-log-python-sdk/pull/14

**Comment by wjo1212** [comment]
merged and close it
