### ISSUE TITLE
extra中字段无法作为fields

### ISSUE THREAD

**Issue by zhanghaofei** [aliyun/aliyun-log-python-sdk#84]
例如log.error("msg", extra={"a": 1})，我想把一些额外信息作为单独字段上传到sls。应该不适用枚举使用户可自定义

**Comment by wjo1212** [comment]
收到，我解决一下

**Comment by wjo1212** [comment]
@zhanghaofei 最新master版本已经支持了，烦请试下。我这里CI跑过也会上传一个版本到pypi
