### ISSUE TITLE
How to get specific log by index when using python SDK

### ISSUE THREAD

**Issue by ChenDongwen** [aliyun/aliyun-log-python-sdk#98]
@wjo1212 Hello!
I'm a aliyun user. When setting consumer options, is there anyway to set the specific index in order to avoid consume too many logs? Or any other smart way to achieve this goal? Thanks!

**Comment by wjo1212** [comment]
@ChenDongwen what do you mean by "specific index"? do you mean the data which meets specific condition. like status_code =400 ?

the consumer API is streaming API which consume all data, you could filter them by yourself. But if most data are not needed, you could use 
get_log_all API which can use Query string to filter them for you. 
https://aliyun-log-python-sdk.readthedocs.io/api.html#aliyun.log.LogClient.get_log_all

**Comment by ChenDongwen** [comment]
@wjo1212 My company has a SLS storing many logs. In over 300 different type of logs I just need 2 of them.
get_log_all API can solve my problem, Thank you!
